basePath: /api/v1
definitions:
  model.ExpireOption:
    enum:
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - Expire6Hours
    - Expire12Hours
    - Expire1Day
    - Expire7Days
  model.ExpiredTypeResponse:
    properties:
      name:
        type: string
      type:
        type: integer
    type: object
  model.PastErrorResponse:
    properties:
      error:
        type: string
    type: object
  model.PasteRequest:
    properties:
      content:
        type: string
      expire:
        $ref: '#/definitions/model.ExpireOption'
    required:
    - content
    - expire
    type: object
  model.PasteResponse:
    properties:
      content:
        type: string
      created_at:
        type: string
      expires_at:
        type: string
      id:
        example: abc123
        type: string
    type: object
  model.ResponseFormat:
    properties:
      data: {}
      error_message:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
  description: JsonJunk
  title: JsonJunk API
  version: "1.0"
paths:
  /paste:
    post:
      consumes:
      - application/json
      description: |-
        새로운 Paste 텍스트를 생성하고 저장합니다.
        expire
      parameters:
      - description: Paste Content
        in: body
        name: paste
        required: true
        schema:
          $ref: '#/definitions/model.PasteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseFormat'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseFormat'
      summary: Paste 생성
      tags:
      - pastes
  /paste/{id}:
    get:
      consumes:
      - application/json
      description: ID를 통해 저장된 Paste 내용을 조회합니다.
      parameters:
      - description: Paste ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PasteResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.PastErrorResponse'
      summary: Paste 조회
      tags:
      - pastes
  /paste/test/list:
    get:
      consumes:
      - application/json
      description: test
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseFormat'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseFormat'
      summary: test
      tags:
      - test
  /paste/type:
    get:
      consumes:
      - application/json
      description: Paste expire type 조회합니다.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.ResponseFormat'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.ExpiredTypeResponse'
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ResponseFormat'
      summary: Paste expire type 조회
      tags:
      - pastes
swagger: "2.0"
